; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
build_src_filter = +<main.cpp>

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
    bogde/HX711 @ ^0.7.5
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/Adafruit NeoPixel @ ^1.12.0
    madhephaestus/ESP32Servo @ ^3.0.0

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = ESP32_COMEDERO.local
upload_flags =
    --auth=comedero2024

[env:esp32dev_wokwi]
extends = env:esp32dev
build_src_filter = -<main.cpp> +<main_wokwi.cpp>

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
upload_protocol = esptool
board_build.flash_size = 16MB
board_build.partitions = min_spiffs.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
board_upload.use_1200bps_touch = true
board_upload.wait_for_upload_port = true
build_src_filter = +<main.cpp>
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
    bogde/HX711 @ ^0.7.5
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/Adafruit NeoPixel @ ^1.12.0
    madhephaestus/ESP32Servo @ ^3.0.0

[env:esp32s3_ota]
extends = env:esp32s3
upload_protocol = espota
upload_port = ESP32_COMEDERO.local
upload_flags = --auth=comedero2024

[env:esp32s3_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
upload_protocol = esptool
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
board_upload.use_1200bps_touch = true
board_upload.wait_for_upload_port = true
build_src_filter = -<main.cpp> -<main_wokwi.cpp> +<test_s3.cpp>
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0